### ISSUE TITLE
Interesting in your work

### ISSUE THREAD

**Issue by zikai1** [Sentient07/DeformationBasis#3]
Hi,

 Thank you for your great work! I am interesting in running and studying the code.  Nevertheless, the pre-processing code to attain the basis function and its gradient seems not public yet, meanwhile, the code regarding shape interpolation part seems not public also.

Could you please share the above codes for interested readers to study, thank you very much.

Best wishes,
Mingyang

**Comment by Sentient07** [comment]
Hi,

You should find basis function initialistion, gradient computation, etc here: https://github.com/Sentient07/DeformationBasis/blob/master/utils/batched_mls_function.py . Regarding the shape interpolation, I'll release it soon. Thanks for your interest and hope that helps

**Comment by zikai1** [comment]
> Hi,
> 
> You should find basis function initialistion, gradient computation, etc here: https://github.com/Sentient07/DeformationBasis/blob/master/utils/batched_mls_function.py . Regarding the shape interpolation, I'll release it soon. Thanks for your interest and hope that helps

Thank you for your kind and timely response. Thank you!
