### ISSUE TITLE
'CorrespondenceEvaluator' package is not provided

### ISSUE THREAD

**Issue by zikai1** [Sentient07/DeformationBasis#4]
Hi,
   When I install the `CorrespondenceEvaluator` package following your instruction in Step 5, the following error emerges. It seems that there is no corresponding repository. 

```
git clone https://github.com/Sentient07/CorrespondenceEvaluator.git && cd CorrespondenceEvaluator && pip install -e .
Cloning into 'CorrespondenceEvaluator'...
remote: Repository not found.
fatal: repository 'https://github.com/Sentient07/CorrespondenceEvaluator.git/' not found
```

Thank you again for your kind help and sharing.

Best wishes,
Mingyang

**Comment by Sentient07** [comment]
Hi, please see this: https://github.com/Sentient07/DeformationBasis/issues/2#issuecomment-1693262525 I still haven't found time but I'll try to release it soon :)

**Comment by zikai1** [comment]
> Hi, please see this: [#2 (comment)](https://github.com/Sentient07/DeformationBasis/issues/2#issuecomment-1693262525) I still haven't found time but I'll try to release it soon :)

Thank you once again! I am forward to your release. Thank you!

**Comment by hanbinbin-web** [comment]
Hello, thank you for your work, have you released this library yet? I can't find it. Can you tell me where to look?
